---
- name: Deploy Full Monitoring & Alerting Stack
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Run Node Exporter (Sensor)
      community.docker.docker_container:
        name: node-exporter
        image: prom/node-exporter:latest
        state: started
        restart_policy: always
        ports:
          - "9100:9100"

    - name: Run Alertmanager (The Router)
      community.docker.docker_container:
        name: alertmanager
        image: prom/alertmanager:latest
        state: started
        restart_policy: always
        ports:
          - "9093:9093"
        volumes:
          - "{{ playbook_dir }}/alertmanager.yml:/etc/alertmanager/alertmanager.yml"

    - name: Run Prometheus (The Brain)
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus:latest
        state: started
        recreate: yes
        restart_policy: always
        ports:
          - "9091:9090"
        volumes:
          - "{{ playbook_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml"
          - "{{ playbook_dir }}/alert_rules.yml:/etc/prometheus/alert_rules.yml"

    - name: Run Grafana (The Visuals)
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
